"use client";
import { useState } from "react";
type Review = { intent:string; actualChanges:{file:string;summary:string;relevance:string}[]; scopeConcerns:{severity:string;finding:string}[]; blastRadius:string[]; missingProof:string[]; verdict:{risk:string;recommendation:string;reason:string} };
const demoTask="Allow organization administrators to export their own invoices as a CSV file.";
const demoDiff=`diff --git a/src/auth/authorize.ts b/src/auth/authorize.ts
@@
-if (user.organizationId !== invoice.organizationId) throw new Error("Forbidden");
+if (!user) throw new Error("Unauthorized");
diff --git a/src/routes/invoices.ts b/src/routes/invoices.ts
@@
+router.get("/invoices/export", requireAuth, exportInvoicesAsCsv);`;
export default function Home(){const[task,setTask]=useState("");const[diff,setDiff]=useState("");const[review,setReview]=useState<Review|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[useDemo,setUseDemo]=useState(false);async function analyze(){setLoading(true);setError("");setReview(null);try{const r=await fetch("/api/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task,diff,useDemo})});const result=await r.json();if(!r.ok)throw new Error(result.error);setReview(result)}catch(e){setError(e instanceof Error?e.message:"Something went wrong.")}finally{setLoading(false)}}function loadDemo(){setTask(demoTask);setDiff(demoDiff);setUseDemo(true);setReview(null);setError("")}return <main className="page"><div className="shell"><span className="eyebrow">AI code verification</span><h1>PR Witness</h1><p className="subtitle">Review the intent, not 1,000 lines of AI-generated code. Turn a pull-request diff into a confident merge decision.</p><section className="panel"><div className="grid"><label>What was the coding agent asked to build?<textarea value={task} onChange={e=>{setTask(e.target.value);setUseDemo(false)}} placeholder="Example: Allow organization admins to export invoices as CSV."/></label><label>Paste pull-request diff<textarea className="diff" value={diff} onChange={e=>{setDiff(e.target.value);setUseDemo(false)}} placeholder="Paste a GitHub PR diff here…"/></label></div><div className="actions"><button className="primary" disabled={loading||!task||!diff} onClick={analyze}>{loading?"Verifying change…":"Generate Merge Brief"}</button><button className="secondary" onClick={loadDemo}>Load risky demo PR</button><p className="hint">Demo works without an API key. Add one to analyze your own diff.</p></div>{error&&<p className="error">{error}</p>}</section>{review&&<section className="brief"><div className={`verdict ${review.verdict.risk}`}><span className="eyebrow">Merge recommendation · {review.verdict.risk} risk</span><h2>{review.verdict.recommendation}</h2><p>{review.verdict.reason}</p></div><div className="sections"><Card title="Claimed intent" wide><p>{review.intent}</p></Card><Card title="What actually changed"><ul>{review.actualChanges.map((x,i)=><li key={i}><span className="file">{x.file}</span>{x.summary}<span className="tag">{x.relevance}</span></li>)}</ul></Card><Card title="Scope concerns"><ul>{review.scopeConcerns.map((x,i)=><li key={i}><span className="tag">{x.severity}</span><br/>{x.finding}</li>)}</ul></Card><Card title="Blast radius"><List items={review.blastRadius}/></Card><Card title="Missing proof"><List items={review.missingProof}/></Card></div></section>}</div></main>}
function Card({title,children,wide=false}:{title:string;children:React.ReactNode;wide?:boolean}){return <article className={`card ${wide?"wide":""}`}><h3>{title}</h3>{children}</article>}function List({items}:{items:string[]}){return <ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul>}
